name: Go sbom generation
on: [ push ]

env:
  IMAGE: ttl.sh/nais/sbom/go
  CONTEXT: ci/golang

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.IMAGE }}:1h
          context: ./${{ env.CONTEXT }}

      - name: Generate, and output SBOM
        uses: ./
        id: sbom
        with:
          image: ${{ env.IMAGE }}@${{ steps.docker_build.outputs.digest }}
          build-context: ${{ env.CONTEXT }}

      - name: Upload SBOM
        uses: actions/upload-artifact@v3
        with:
          name: sbom
          path: ${{ steps.sbom.outputs.sbom-path }}