name: Gradle Salsa Action
on: [ push ]

env:
  IMAGE: ttl.sh/salsa/sbom/gradletestapp
  CONTEXT: ci/jvm

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.IMAGE }}:1h
          context: ./${{ env.CONTEXT }}

      - uses: actions/setup-java@v3
        with:
          java-version: 15
          distribution: 'zulu'
          cache: 'gradle'

      - name: Generate, sign and upload SBOM
        uses: ./
        with:
          image: ${{ env.IMAGE }}@${{ steps.docker_build.outputs.digest }}
          build-context: ${{ env.CONTEXT }}/gradle
          key: ${{ env.KEY }}